services:
  app:
    build: .
    container_name: padel_reservation_app
    ports:
      - "3000:3000"   # HTTP
      - "3001:3001"   # HTTPS
    volumes:
      - .:/usr/src/app
      - ./cert:/usr/src/app/cert
      - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: padel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: padel_reservation
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  dbdata:
